### ISSUE TITLE
[ERROR] Could not find matching PulseAudio input source

### ISSUE THREAD

**Issue by fiik346** [rom1v/usbaudio#12]
I don't know how to fix it.
```
taufik@taufik-HP-Notebook:/etc/bluetooth$ usbaudio
[INFO] Device: [2717:ff88] d4f59a3f7d24
[INFO] Audio forwarding enabled
[INFO] Waiting for input source...
[ERROR] Could not find matching PulseAudio input source
taufik@taufik-HP-Notebook:/etc/bluetooth$
```

**Comment by rom1v** [comment]
Is your device Android 8 or above?

**Comment by fiik346** [comment]
my android version is 9

**Comment by fiik346** [comment]
I use kubuntu 18.04.3

**Comment by rom1v** [comment]
That's the reason, AOA Audio is deprecated since Android 8.
https://source.android.com/devices/accessories/aoa2

**Comment by fiik346** [comment]
You have a solution?

**Comment by rom1v** [comment]
AOA Audio is deprecated, so it's obsolete.

The Android 10 audio API must be investigated: https://github.com/Genymobile/scrcpy/issues/14#issuecomment-523071057

**Comment by billyboh** [comment]
I've got the same problem and I'm using Android 7.0
This is the output:

donnie@tangent:~> usbaudio 
[INFO] Device: [12d1:107e] 6AGDU17807002446
[INFO] Audio forwarding enabled
[INFO] Waiting for input source...
[ERROR] Could not find matching PulseAudio input source

I'm running it on openSuse Leap 15.1

**Comment by laichiaheng** [comment]
```
[laichiaheng@Julian-PC ~]$ usbaudio
[INFO] Device: [04e8:6860] 52003119fe5d2547
[INFO] Audio forwarding enabled
[INFO] Waiting for input source...
[ERROR] Could not find matching PulseAudio input source
[laichiaheng@Julian-PC ~]$ usbaudio
[ERROR] Could not read device serial
[ERROR] Could not find device
```

**Comment by MidnightQuery** [comment]
huizichin@debian:~$ usbaudio
[INFO] Device: [12d1:107d] 7PB9X17B30G00249
[INFO] Audio forwarding enabled
[INFO] Waiting for input source...
[ERROR] Could not find matching PulseAudio input source

Same error for me, also i noticed that when i run usbaudio command the usb configuration on my phone become audio and adb doesnt seem to work when in audio mode.
using android 7.0

**Comment by taufik-nurhidayat** [comment]
Hei, it was solved in latest scrcpy. But i was change my phone to android 13
