### ISSUE TITLE
Audio getting chuncky, delayed and VLC throws delay errors

### ISSUE THREAD

**Issue by maxsupermanhd** [rom1v/usbaudio#15]
```
max@[~/usbaudio/x]$ ./usbaudio --live-caching 20
[INFO] Device: [18d1:2d03] 4200d117e4f0547d
[INFO] Audio forwarding enabled
[INFO] Matching PulseAudio input source found: 2 (18d1:2d03) SAMSUNG_SAMSUNG_Android_4200d117e4f0547d
[INFO] Playing pulse://2
VLC media player 3.0.8 Vetinari (revision 3.0.8-0-gf350b6b5a7)
[000055c71da8e4a0] dummy interface: using the dummy interface module...
[00007f3ea4000c40] main input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 20 ms)
[00007f3ea4000c40] main input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 73 ms)
[00007f3ea4000c40] main input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 134 ms)
[00007f3ea4000c40] main input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 144 ms)
...
```
Tried to scale `--live-caching` from 20 to 80 and no result. Using without scrcpy. Maybe it's my Alsa/Pulse issue...

**Comment by IsaahE** [comment]
make sure to change the "select usb configuration" in developer settings or in the drop down Android System dialog to "MTP" or "Transfer Files" same thing different name

**Comment by IsaahE** [comment]
just tried on charging mode and MTP with normal "usbaudio" command and they both lagged, the other command "usbaudio -n" has way less latency and never stuttered one time

**Comment by Samega7Cattac** [comment]
I had the same issue but while recording it doesn't show

**Comment by IsaahE** [comment]
> I had the same issue but while recording it doesn't show

Have you tried "usbaudio -n" and what doesn't show up?

**Comment by Samega7Cattac** [comment]
sorry.
I mean it shows up correctly when I recorded with obs even if tons of lag on real time, but was ok in the recording

**Comment by maxsupermanhd** [comment]
So this is kinda audio server playback issue?

**Comment by IsaahE** [comment]
> sorry.
> I mean it shows up correctly when I recorded with obs even if tons of lag on real time, but was ok in the recording

Ah nice job I hadn't realized that the audio was actually fine.

**Comment by IsaahE** [comment]
> sorry.
> I mean it shows up correctly when I recorded with obs even if tons of lag on real time, but was ok in the recording



> So this is kinda audio server playback issue?

Probably
