### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by SabbirRahmanSR** [rom1v/usbaudio#27]
My phone 6.0, 23 
So, SDK very old but I want to used sndcpy apk,
My phone don't open apk, so please make 6.0 sndcpy apk, 

Thank you 
@SabbirRahmanSR [SabbirRahmanSR](https://www.instagram.com/sabbir_rahman_sr)

**Comment by rom1v** [comment]
That's not possible, the principle is to use a new API from Android 10.
