### ISSUE TITLE
Any plans to support PipeWire

### ISSUE THREAD

**Issue by Omnifarious** [rom1v/usbaudio#34]
A lot of distributions are ditching PulseAudio for pipewire. Any plans to support it?

**Comment by rom1v** [comment]
scrcpy uses SDL, which has several backends.

If pipewire is not automatically selected and you want to force it, set `SDL_AUDIODRIVER=pipewire`.

https://wiki.libsdl.org/SDL2/FAQUsingSDL#how_do_i_choose_a_specific_audio_driver
