### ISSUE TITLE
Setting adb executable path

### ISSUE THREAD

**Issue by matheusfillipe** [rom1v/usbaudio#6]
I'm on Ubuntu 18.04 LTS,  using the adb from android sdk's (from android studio) for scrcyp lauching setting the adb variable to my custom path but that doesn't work with usbauio:

ADB="/home/matheus/bin/adb" usbaudio
[ERROR] Could not find device

Thats the only message I get... even thought I have it:

adb devices
List of devices attached
192.168.0.113:5555      device

And scrcpy is working. That should be a feature or maybe I didn't just found it out yet..

**Comment by rom1v** [comment]
Did you tested several times, to confirm the error occurs only when you use the ADB env variable? I guess the problem is independant.

**Comment by matheusfillipe** [comment]
The variable ADB there doesn't change nothing, I have tested without it. It Should be possible to set the ADB variable path like it is with scrcpy. 

So this is sort of a feature request, in case this isn't possible in other way.

If it isn't clear enough yet, I have an adb executable in /usr/bin/adb (created by the android-tools Ubuntu package) and another in /home/matheus/bin/adb, which is a symlink do my Android SDK abd installed with Android studio. The first is version 39 and the last is 41, so I would need usbaudio to use the last one instead of the first, which is what it is probably using by default. How to do that?

Well, I believe that's the issue here, hence I couldn't find any info for setting a custom ADB path for usbaudio. Maybe I just didn't find that it is possible to launch it with scrcpy automatically, then both would use the set ADB, or during the build process I could change this somehow?

**Comment by rom1v** [comment]
> The variable ADB there doesn't change nothing, I have tested without it. It Should be possible to set the ADB variable path like it is with scrcpy.

Oh, yes, usbaudio does not use `adb` at all.

>     192.168.0.113:5555 device

And it only works over USB.

**Comment by matheusfillipe** [comment]
Hah! Hence the name usbaudio :joy: 

Everything makes sense now.... So I guess there are no options for wireless audio...
