### ISSUE TITLE
Not working (Pipe error)

### ISSUE THREAD

**Issue by shigutso** [rom1v/usbaudio#8]
```
$ usbaudio
[INFO] Device: [2833:0083] XXXXXXXXXXXX
[ERROR] Pipe error
[ERROR] Could not get AOA protocol version
[ERROR] Could not forward audio
```

My setup:
Kubuntu 19.04 x86_64

Tried running before and after running `scrcpy`, but I get the same error. `scrcpy` runs fine.
Also tried as root, but same error.

Any help? Thanks!

EDIT: forgot to say that I'm using a Oculus Quest

**Comment by shigutso** [comment]
https://github.com/rom1v/usbaudio/commit/76b20cbb72260d673f0bc8a040b3b93c9bbd555a

**Comment by StackDoubleFlow** [comment]
Should this be an issue? The Oculus Quest is running android 7.1.1 (API 25) but the issue still persists.

**Comment by rom1v** [comment]
sndcpy requires Android 10.
